# Generated by Django 4.1.3 on 2023-05-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, default='', height_field='height_field', null=True, upload_to='images/', width_field='width_field'),
        ),
    ]
