# Generated by Django 4.1.3 on 2023-05-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(default=1, height_field='height_field', upload_to='images/', width_field='width_field'),
            preserve_default=False,
        ),
    ]
